- src/types/wiki.ts
- adds mediaType to media type and exported media type enum
> tweeked wiki types to allow add media type to medias

- src/types/wiki.ts
- Adds linked wikis type to wiki type
- exports LinkedWikiKey enum 
- exports LinkedWikis Type
> Adds linked wikis type to wiki type

- .changeset/happy-news-peel.md
- src/types/wiki.ts
added medium into common metaId
> added medium into common metaId

- .changeset/stupid-rocks-heal.md
- src/index.ts
- src/types/wikiBuilder.ts
- Adds wiki builder generic  to easily construct custom wiki types
> Adds wiki builder generic 

- .changeset/witty-rabbits-help.md
- src/types/wiki.ts
- adds optional events to wiki object
- adds export to EventsTypes
> Adds events type to wiki

- .changeset/loud-poets-matter.md
- src/types/wiki.ts
- adds Events to validator codes
> Adds events to validator code

- .changeset/spicy-beers-mate.md
- src/types/wiki.ts
This PR updates the social media link of the common metaIds
> adding social links to commonMetaIds

- .changeset/spotty-planes-help.md
- src/types/wiki.ts
- **Add event location common Id 
- **closes https://github.com/EveripediaNetwork/issues/issues/2281
- **Event location can be added in wikis**
> Add events location metadata id

- src/types/wiki.ts
- Allows tik tok links to be added to wiki pages.
> ## Adds Tiktok to ``CommonMetaIds``

- src/types/wiki.ts
Reverts EveripediaNetwork/iq-utils#26
> Revert "## Adds Tiktok to ``CommonMetaIds``"

- .changeset/spotty-planes-help.md
- src/types/wiki.ts
- **Allows addition of events spanning multiple days
- **closes https://github.com/EveripediaNetwork/issues/issues/2281
> Multi date events

- .changeset/is-deeped-equal.md
- package.json
- src/lib/isDeepEqual.ts
Updating the library to add function for deep comparision
This function is use to compare deeply
> done adding logic for deep comparison

- .changeset/thick-flowers-work.md
- CHANGELOG.md
- package.json
- src/types/wiki.ts
This change updates Explorer links  CommonMetaIds types
> Explorers link common metaids

- .changeset/rude-poems-wash.md
- src/types/wiki.ts
- **What kind of change does this PR introduce?** types update
closes https://github.com/EveripediaNetwork/issues/issues/2905
> added a new explorer

- .changeset/rude-wombats-try.md
- src/types/wiki.ts
- src/types/wikiBuilder.ts
Adds new simplified type for wiki for founder wiki and blockchain
It doesn't include founderWikis and blockchainWikis
Adds  founderWikis and blockchainWikis
> Adds new simplified type for wiki for founder wiki and blockchain

- .changeset/chatty-yaks-relax.md
- .changeset/stupid-queens-deny.md
- src/data/constants.ts
- src/lib/checkWikiValidity.ts
- src/lib/isDeepEqual.ts
- src/lib/wikiScore.ts
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...) Adds isValidWiki check
It doesn't have a way to validate wiki
It adds validity check in utils
Fixes https://github.com/EveripediaNetwork/issues/issues/3031
> Adds isValidWiki check

- .changeset/update-event-action-types.md
- src/types/wiki.ts
Update Event Action to cover more action
> update event action types

- .changeset/swimming-otter.md
- src/types/wiki.ts
- **Initially, no location per event**
- **Currently, location is optionally added per event date/date-range**
> Event location

- .changeset/swimming-otter.md
- src/types/wiki.ts
Reverts EveripediaNetwork/iq-utils#55
> Revert "Event location"

- .changeset/slimy-grapes-turn.md
- .changeset/swift-buckets-do.md
- src/index.ts
- src/lib/checkWikiValidity.ts
- **What kind of change does this PR introduce?** Add export to existing functions in checkWikiValidity.ts
- **What is the new behavior (if this is a feature change)?** Allows use of internal functions
> Add export to existing functions in checkWikiValidity.ts

- .changeset/clever-moons-tan.md
- .changeset/itchy-wombats-doubt.md
- src/lib/wikiScore.ts
- **What kind of change does this PR introduce?** Fix regex in getHostnameFromRegex function
- **What is the new behavior (if this is a feature change)?** Update Regex
> Fix regex in getHostnameFromRegex function

- biome.json
- Adds quick fix for: improved biome config
> improved biome config

- .changeset/quick-nails-argue.md
- src/lib/wiki-helpers.ts
- Adds quick fix for: fix graphql endpoint
> fix graphql endpoint

- .changeset/rare-weeks-learn.md
- src/lib/wiki-helpers.ts
- Adds quick fix for: use function syntax in wiki helpers
> use function syntax in wiki helpers

- .changeset/twelve-rabbits-wonder.md
- src/lib/wiki-helpers.ts
- src/playground.ts
- Adds quick fix for: fix incorrect type assuption for getExplorers
> fix incorrect type assuption for getExplorers

- src/playground.ts
- Adds quick fix for: removes playground file from repo
> removes playground file from repo

- .changeset/tricky-pumas-leave.md
- src/lib/wiki-helpers.ts
- src/schema/index.ts
- Adds quick fix for: remove invalid metadata instead of raising errors
> remove invalid metadata instead of raising errors

- .changeset/eleven-bats-move.md
- package.json
- pnpm-lock.yaml
- src/lib/wiki-helpers.ts
- Adds quick fix for: add cache to get explorers
> add cache to get explorers

- .changeset/quick-trainers-press.md
- package.json
- pnpm-lock.yaml
- src/lib/wiki-helpers.ts
- Adds quick fix for: remove cache for getExplorers
> remove cache for getExplorers

- .changeset/strong-mugs-smell.md
- package.json
- pnpm-lock.yaml
- src/lib/wiki-helpers.ts
- Adds quick fix for: add cache to get explorers with axios cache interceptor
> add cache to get explorers with axios cache interceptor

- .changeset/wild-owls-end.md
- src/schema/index.ts
- Adds quick fix for: make media size string or number
> make media size string or number

- src/schema/index.ts
- **What kind of change does this PR introduce?** Fix build error
> resolve build error
